# Generated by Django 3.0.3 on 2021-02-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transferform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=50)),
                ('receiver_name', models.CharField(max_length=50)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
    ]
