# Generated by Django 3.0.3 on 2021-02-08 18:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0003_transferform_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferform',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
